Первый пулл реквест
frontend-park-mail-ru/2018_1_Techokek pull request #1
Opened 2018-02-27 17:18 UTC by VitalyCherkov

2018-02-27 20:12 UTC, martinkomitsky requested changes
Нужно исправить все замечания, получив новый опыт, пройти по всему пулл реквесту и исправить повторяющиеся моменты.

2018-02-27 20:12 UTC, martinkomitsky commented on package.json
> +    "start": "DEBUG=* node server/index.js"
а что за `*`?

2018-02-27 20:12 UTC, martinkomitsky commented on public/index.html
> +<script type="module" src="js/modules/downsections/abstractSection.js"></script>
Нужно везде сделать абсолютные пути

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +    _updateHidden() {
Давайте соблюдать кодстайл. Блоки хорошо всегда размечать фигурными скобками, даже если они содержат всего одну строку, помимо этого надо ставить пробелы после операторов:
```
if (condition) {
  //
} else {
  //
}

for (;;) {
  //
}

```
Это делается для того, чтобы было удобнее работать в гите: при изменении логики будет меньше дифф, еще это помогает избегать ошибок при расширении ветки в случае с `if`.

Нужно пробежаться и исправить по всем файлам.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                templateFunction: window.signupformTmplTemplate,
что за наименование `tmplTemplate`? Нельзя оставить что-то одно?

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                form.hidden = !form.hidden;
Плохо. Предлагаю эту строку вынести в функцию `toggle`, которую можно расположить на 24 строке класса `AbstractForm `. И прямой доступ к полю класса заменить на вызов сеттера, описанного выше.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +            new AbstractForm({
Можно весь этот блок зарефакторить: оба объекта взять и перенести в какое-нибудь отдельное поле этого класса, например, массива `this.formOptions`. А внутри функции `_createForms` сделать следующее:
```
this._forms = this.formOptions.map(formOption=> {
  return new AbstractForm(formOption);
});
```

Кроме того, если в обработчиках не планируется ничего добавлять, можно сделать так:
`changeFormSlot: this.changeForms`. 
Текущая запись избыточна и пока не имеет смысла, похожа на копипасту, чего мы стараемся избегать.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/components/gloabalData.js
> +    get initialTabs() {
Если ничего не планируется делать внутри, можно сразу вернуть стрелочной функцией значение.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/downscreen/downscreen.js
> +            let current = new section.sectionSelect('.' + section.jsClass);
У нас же есть шаблонные строки. Можно так:
```
`.${section.jsClass}`
```

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/downscreen/downscreen.js
> +        this._sections = [];
Этот цикл тоже можно переписать в `.map`, как я показал выше.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/init/init.js
> +        this._downscreen = new Downscreen('.js-down-screen');
Наверное, было бы логичнее сначала создать экземпляры, а потом уже последовательно вызывать метод `render`. Суть в том, что если что-то в момент создания объектов взорвется, браузер не остановится на недорисованном интерфейсе, смущая пользователя, а просто упадет в исходном состоянии. Но не принципиально.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/tabbar/tabbar.js
> +            let {title, jsClass, _} = tab;
Как я понял, эти переменные тут не изменяются, можно их сделать `const`.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/tabbar/tabbar.js
> +    _tabClickedHandler(evt, tabElement) {
Гармоничней называть функции, начиная с глаголов, типа `handleTabClick`

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/tabbar/tabbar.js
> +        if(Boolean(this._currentTab)){
Что именно здесь проверяется? Если наличие объекта, то и без `Boolean` сработает.

2018-02-27 20:12 UTC, martinkomitsky commented on public/js/modules/tabbar/tabbar.js
> +        getLinkedSection(tabElement).hidden = false;
Подозреваю, что тут можно будет заюзать `.toggle()`.

2018-02-27 20:56 UTC, VitalyCherkov commented on public/js/modules/authSignup/authSignup.js
> +                form.hidden = !form.hidden;
Т.е. преобразовать в form.toggle()?
И еще, где здесь прямое обращение к полю класса? hidden - это ведь и есть сеттер

2018-02-27 20:58 UTC, VitalyCherkov commented on public/js/modules/authSignup/authSignup.js
> +                templateFunction: window.signupformTmplTemplate,
Это происходит из-за автоматического именования шаблонов,
файл *.pug преобразуется в *.js, внутри которого функция *Template(), но т.к файл шаблона и так помечается как .tmpl.pug, то функция получается *TmplTemplate(). Я хочу это изменить как-то, но пока не знаю как.

2018-02-27 21:00 UTC, VitalyCherkov commented on public/js/modules/authSignup/authSignup.js
> +            new AbstractForm({
Возможно, я ошибаюсь, но дело в том, что когда я так передавал, то внутри объекта формы эта функция в качестве this принимала форму, а не модуль из двух форм, из-за чего была ошибка, из-за чего пришлось обернуть. Но я еще раз проверю, но вроде как было именно так...

2018-02-28 05:38 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                form.hidden = !form.hidden;
` form.hidden = !form.hidden;`
Что происходит в этой строчке?

2018-02-28 05:41 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                templateFunction: window.signupformTmplTemplate,
Можно попробовать не помечать как `.tmpl.pug`, а просто `.pug`, думаю, не будет проблема поменять конфиги

2018-02-28 05:43 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +            new AbstractForm({
Если ты про участок с `changeFormSlot: this.changeForms`, то для уверенности в конце можно добавить `.bind(this)` и понять, почему это работает/не работает

2018-02-28 06:11 UTC, VitalyCherkov commented on public/js/modules/authSignup/authSignup.js
> +                form.hidden = !form.hidden;
я через сеттер hidden меняю свойство _hidden, полученное из геттера hidden) Но там нужно по-другому сделать. У элемента _el есть просто свойство hidden, которое можно менять напрямую. Переделаю

2018-02-28 13:58 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                form.hidden = !form.hidden;
Все, я понял)) сорян))

2018-02-28 14:41 UTC, VitalyCherkov commented on public/js/modules/authSignup/authSignup.js
> +                templateFunction: window.signupformTmplTemplate,
я так помечал, чтобы в gitignore добавить .tmpl.js, которые рендерятся, но если я буду полмечать только .t, то будут TTemplate. Как такой вариант?

2018-02-28 15:33 UTC, VitalyCherkov commented on public/js/modules/tabbar/tabbar.js
> +        getLinkedSection(tabElement).hidden = false;
Там toggle использовать нельзя, т.к. это dom элемент

2018-02-28 15:47 UTC, martinkomitsky commented on public/js/modules/authSignup/authSignup.js
> +                templateFunction: window.signupformTmplTemplate,
Да ладно, это полумеры. Если не получается пока, то можно забить, не принципиально.

2018-02-28 16:13 UTC, martinkomitsky commented on public/js/modules/tabbar/tabbar.js
> +        getLinkedSection(tabElement).hidden = false;
я про тот тогл, который предлагал написать. Да, забей

2018-03-03 08:47 UTC, martinkomitsky approved these changes
сас

2018-03-03 08:47 UTC, merged

2018-03-03 09:52 UTC, avtyul commented on public/js/components/http.js
> +    doGet({url = '/', callback = noop, data = {}} = {}) {
`utils.noop`